apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerboot-app-test
spec:
  selector:
    matchLabels:
      app: dockerboot-app-test
  replicas: 3
  template:
    metadata:
      labels:
        app: dockerboot-app-test
    spec:
      containers:
        - name: dockerboot-app-test
          image: dockerboot-app:test
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dockerboot-app-test
spec:
  selector:
    app: dockerboot-app-test
  type: LoadBalancer
  ports:
    - port: 9093
      targetPort: 8080